apiVersion: v1
data:
  MYSQL_ROOT_PASSWORD: cm9vdF9wYXNzd29yZA== 
  MYSQL_DATABASE: ZHJ1cGFsLWRhdGFiYXNl 
  MYSQL_USER: cm9vdA==
kind: Secret
metadata:
  name: drupal-mysql-secret
  namespace: default
type: Opaque
